version: '3'

services:
  gemindz-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./instance:/app/instance
      - ./src/instance:/app/src/instance
      - ./src:/app/src
    ports:
      - 5000:5000
    command: ["python", "./src/main.py"]
